import { EtudiantModel } from '../Model/etudiant-model';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { JwtHelperService } from '@auth0/angular-jwt';
import { envVars } from 'src/envVars';

@Injectable({ providedIn: 'root'
})
export class AuthService {


  headers = new HttpHeaders({Accept: '*/*'});
  etudiantCollection = [
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Philosophie",
      "typeEtudiant": "ancien",
      "moyenne": 12,
      "numero": "1995005VU",
      "nom": "MANDIONE",
      "prenoms": "Bienvenue Mathurin",
      "dateNaissance": "27/09/1973",
      "lieuNaissance": "MOUIT"
    },
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Philosophie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995003LM",
      "nom": "DIOUF",
      "prenoms": "Blaise",
      "dateNaissance": "29/11/1972",
      "lieuNaissance": "NGOHE POFINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Philosophie",
      "typeEtudiant": "ancien",
      "moyenne": 10,
      "numero": "1995004DJ",
      "nom": "GUEYE",
      "prenoms": "Mamadou",
      "dateNaissance": "01/08/1969",
      "lieuNaissance": "SAINT-LOUIS"
    },
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 1 Philosophie",
      "typeEtudiant": "ancien",
      "moyenne": 5,
      "numero": "1996008AI",
      "nom": "DIENE",
      "prenoms": "Moussa Ramata",
      "dateNaissance": "13/03/1973",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123456789123",
      "niveauFormation": "Licence 1 Philosophie",
      "typeEtudiant": "nouveau bachelier",
      "moyenne": 12,
      "numero": "202006TKN",
      "nom": "THIAW",
      "prenoms": "Pode",
      "dateNaissance": "03/04/1996",
      "lieuNaissance": "DJILOR SALOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Philosophie",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123456789123",
      "niveauFormation": "Licence 1 Philosophie",
      "typeEtudiant": "nouveau bachelier",
      "moyenne": 12,
      "numero": "202006TKM",
      "nom": "SENE",
      "prenoms": "Daba",
      "dateNaissance": "25/03/1995",
      "lieuNaissance": "DJILOR SALOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Medecine",
      "etablissement": "F.M.P.O.",
      "numIdentite": "123654789",
      "niveauFormation": "Troisième Cycle des Etudes Médicales (Thèse)",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700AU6",
      "nom": "DIENE",
      "prenoms": "Ousmane Henry",
      "dateNaissance": "19/04/1978",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Medecine",
      "etablissement": "F.M.P.O.",
      "numIdentite": "123654789",
      "niveauFormation": "Troisième Cycle des Etudes Médicales (Thèse)",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700AVY",
      "nom": "BA",
      "prenoms": "Pape Yakhya",
      "dateNaissance": "25/06/1978",
      "lieuNaissance": "MEDINA GOUNASS"
    },
    {
      "sessionId": "Session 1",
      "departement": "Medecine",
      "etablissement": "F.M.P.O.",
      "numIdentite": "123654789",
      "niveauFormation": "Troisième Cycle des Etudes Médicales (Thèse)",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700AOV",
      "nom": "TRAORE",
      "prenoms": "Mariétou",
      "dateNaissance": "09/12/1976",
      "lieuNaissance": "BAMAKO"
    },
    {
      "sessionId": "Session 1",
      "departement": "Medecine",
      "etablissement": "F.M.P.O.",
      "numIdentite": "123654789",
      "niveauFormation": "Quatrième Année du Deuxième Cycle des Etudes Médicales",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700ATN",
      "nom": "DIOP",
      "prenoms": "Mbaye",
      "dateNaissance": "27/07/1971",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HD7",
      "nom": "SAMBE",
      "prenoms": "Amy Collé",
      "dateNaissance": "22/12/1990",
      "lieuNaissance": "MBOUR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HRL",
      "nom": "SYLL",
      "prenoms": "Ibrahima",
      "dateNaissance": "04/06/1989",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HK7",
      "nom": "NDIAYE",
      "prenoms": "Mansor",
      "dateNaissance": "20/11/1991",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HHE",
      "nom": "DIOUF",
      "prenoms": "Youssou",
      "dateNaissance": "01/08/1992",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HDF",
      "nom": "DIA",
      "prenoms": "Abdoulaye",
      "dateNaissance": "31/05/1991",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HS6",
      "nom": "VONIANE",
      "prenoms": "Papa Moussa",
      "dateNaissance": "08/03/1992",
      "lieuNaissance": "RUFISQUE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HDL",
      "nom": "DIACK",
      "prenoms": "Alpha Ciré",
      "dateNaissance": "04/01/1992",
      "lieuNaissance": "TIVAOUANE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104H9H",
      "nom": "BA",
      "prenoms": "Abdoulaye",
      "dateNaissance": "14/07/1991",
      "lieuNaissance": "YEUMBEUL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104H9H",
      "nom": "BA",
      "prenoms": "Abdoulaye",
      "dateNaissance": "14/07/1991",
      "lieuNaissance": "YEUMBEUL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HET",
      "nom": "DIEYE",
      "prenoms": "Badara",
      "dateNaissance": "27/06/1992",
      "lieuNaissance": "BABA GARAGE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HQZ",
      "nom": "SEYE",
      "prenoms": "Mouhamadoul Mokhtar",
      "dateNaissance": "19/01/1994",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HQD",
      "nom": "SECK",
      "prenoms": "Moustapha",
      "dateNaissance": "06/03/1992",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HQA",
      "nom": "SAMBA",
      "prenoms": "Cheikh Sadibou",
      "dateNaissance": "04/11/1992",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HPY",
      "nom": "NIANG",
      "prenoms": "Mouhamed Al Malick",
      "dateNaissance": "14/10/1992",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HPE",
      "nom": "NDOYE",
      "prenoms": "Ndèye Fatou",
      "dateNaissance": "11/01/1991",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HJS",
      "nom": "NDAO",
      "prenoms": "Bruno François Mamour",
      "dateNaissance": "06/01/1993",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HIE",
      "nom": "MBODJ",
      "prenoms": "Oumou Kaltoum",
      "dateNaissance": "17/10/1992",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HI9",
      "nom": "FALL",
      "prenoms": "Souaïbou",
      "dateNaissance": "27/10/1993",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HGW",
      "nom": "DIOP",
      "prenoms": "Papa Boubacar",
      "dateNaissance": "21/09/1993",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HFE",
      "nom": "DIOP",
      "prenoms": "Babacar",
      "dateNaissance": "16/03/1993",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HE7",
      "nom": "DIENG",
      "prenoms": "Ahmadou Mbacké",
      "dateNaissance": "21/01/1994",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104H9W",
      "nom": "BARRY",
      "prenoms": "Mamadou Telli",
      "dateNaissance": "04/11/1993",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HQT",
      "nom": "SENE",
      "prenoms": "Diomaye",
      "dateNaissance": "07/07/1992",
      "lieuNaissance": "SALY"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HJI",
      "nom": "NADIELINE",
      "prenoms": "Olivier Christian",
      "dateNaissance": "15/11/1992",
      "lieuNaissance": "MBAO"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HPM",
      "nom": "NGOM",
      "prenoms": "Oumar",
      "dateNaissance": "22/05/1992",
      "lieuNaissance": "MALICOUNDA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HQV",
      "nom": "SENE",
      "prenoms": "Mor Tine",
      "dateNaissance": "14/06/1992",
      "lieuNaissance": "DIAMAGUENE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HJY",
      "nom": "NDIAYE",
      "prenoms": "El Hadji Malick",
      "dateNaissance": "06/04/1991",
      "lieuNaissance": "PARCELLES ASSAINIES"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HI5",
      "nom": "DJIGO",
      "prenoms": "Aïssata",
      "dateNaissance": "20/03/1993",
      "lieuNaissance": "DIOURBEL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104H9Z",
      "nom": "BEYE",
      "prenoms": "Babacar",
      "dateNaissance": "30/03/1991",
      "lieuNaissance": "LOUGA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104H9Z",
      "nom": "BEYE",
      "prenoms": "Babacar",
      "dateNaissance": "30/03/1991",
      "lieuNaissance": "LOUGA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HRX",
      "nom": "TRAORE",
      "prenoms": "Amady",
      "dateNaissance": "08/12/1991",
      "lieuNaissance": "MANDERA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HF3",
      "nom": "DIOP",
      "prenoms": "Alioune",
      "dateNaissance": "05/01/1991",
      "lieuNaissance": "MECKHE - VILLAGE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HF8",
      "nom": "DIOP",
      "prenoms": "Ousseynou",
      "dateNaissance": "26/05/1991",
      "lieuNaissance": "SANEINTE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HH7",
      "nom": "DIOUF",
      "prenoms": "Mohamed",
      "dateNaissance": "27/02/1992",
      "lieuNaissance": "SEBIKHOTANE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HA0",
      "nom": "CISSE",
      "prenoms": "Bakary",
      "dateNaissance": "18/03/1991",
      "lieuNaissance": "WAOUNDE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HH1",
      "nom": "DIOUF",
      "prenoms": "El Hadji Bakary",
      "dateNaissance": "10/06/1990",
      "lieuNaissance": "ZIGUINCHOR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HIC",
      "nom": "KEBE",
      "prenoms": "Alioune Ibnou Abatalib",
      "dateNaissance": "26/11/1990",
      "lieuNaissance": "KAOLACK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Génie Electrique",
      "etablissement": "E.S.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Diplôme Universitaire de Technologie en Génie Electrique",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "201104HEN",
      "nom": "DIENG",
      "prenoms": "Cheikhou Laye",
      "dateNaissance": "09/09/1991",
      "lieuNaissance": "KAOLACK"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995005GG",
      "nom": "FAYE",
      "prenoms": "Fatou",
      "dateNaissance": "28/09/1966",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950051B",
      "nom": "MBENGUE",
      "prenoms": "Mamadou",
      "dateNaissance": "10/06/1973",
      "lieuNaissance": "MBOULA"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950028Q",
      "nom": "FAYE",
      "prenoms": "Amath",
      "dateNaissance": "23/01/1974",
      "lieuNaissance": "GNIBY"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995004HU",
      "nom": "BITEYE",
      "prenoms": "Ami  Colé",
      "dateNaissance": "06/02/1973",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995004FW",
      "nom": "THIAM",
      "prenoms": "Amadou",
      "dateNaissance": "12/01/1972",
      "lieuNaissance": "NDOFFANE"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Diplôme Probatoire à l'Inspectorat",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995005RW",
      "nom": "DIAGNE",
      "prenoms": "Abdoulaye",
      "dateNaissance": "05/09/1973",
      "lieuNaissance": "KAOLACK"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995005UG",
      "nom": "MENDY",
      "prenoms": "Martignou",
      "dateNaissance": "12/11/1967",
      "lieuNaissance": "MPACK"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995002EA",
      "nom": "SENE",
      "prenoms": "Jean Paul",
      "dateNaissance": "04/05/1971",
      "lieuNaissance": "KONGOLY"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950000X",
      "nom": "CISSE",
      "prenoms": "Aliou",
      "dateNaissance": "08/06/1976",
      "lieuNaissance": "DARSALAM CHERIF"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950056S",
      "nom": "DIALLO",
      "prenoms": "Souleymane",
      "dateNaissance": "13/10/1974",
      "lieuNaissance": "BANDOULOU"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995001O0",
      "nom": "DIOP",
      "prenoms": "Adam",
      "dateNaissance": "02/01/1967",
      "lieuNaissance": "NDOFFANE"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "2ème Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995003ET",
      "nom": "DIALLO",
      "prenoms": "Abdoulaye Adama",
      "dateNaissance": "30/03/1970",
      "lieuNaissance": "SINTHIOU DANGDE"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950012K",
      "nom": "DIENG",
      "prenoms": "Khadim",
      "dateNaissance": "05/01/1975",
      "lieuNaissance": "THIENABA"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1997008YW",
      "nom": "MBOW",
      "prenoms": "Badara",
      "dateNaissance": "08/10/1959",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950010F",
      "nom": "SEYE",
      "prenoms": "El  Hadji Fallou",
      "dateNaissance": "10/01/1974",
      "lieuNaissance": "PATTAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950050O",
      "nom": "BOCOUM",
      "prenoms": "Mouhamadou",
      "dateNaissance": "15/04/1974",
      "lieuNaissance": "SALIKEGNE"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995004TY",
      "nom": "NDIAYE",
      "prenoms": "Oumar Adama Cire",
      "dateNaissance": "30/01/1972",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "'Inspecteurs",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "1ère Année Certificat d'Aptitude aux fonctions d'Inspecteur de l'Enseignement Elémentaire Français",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19960085R",
      "nom": "LY",
      "prenoms": "Djibril",
      "dateNaissance": "02/01/1977",
      "lieuNaissance": "RICHARD - TOLL"
    },
    {
      "sessionId": "Session 2",
      "departement": "Droit Privé",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 2 Sciences Juridiques Parcours Professionnel",
      "typeEtudiant": "ancien",
      "moyenne": 6,
      "numero": "1996007OM",
      "nom": "DIA",
      "prenoms": "Adja Fatou",
      "dateNaissance": "20/11/1976",
      "lieuNaissance": "THIES"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995002II",
      "nom": "NIANG",
      "prenoms": "Talla",
      "dateNaissance": "27/08/1974",
      "lieuNaissance": "KEBEMER"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 5,
      "numero": "1995004H7",
      "nom": "DIALLO",
      "prenoms": "Djiby",
      "dateNaissance": "11/07/1973",
      "lieuNaissance": "VELINGARA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995004QU",
      "nom": "DIOUF",
      "prenoms": "Wagane",
      "dateNaissance": "17/07/1970",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995004QU",
      "nom": "DIOUF",
      "prenoms": "Wagane",
      "dateNaissance": "17/07/1970",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995004QU",
      "nom": "DIOUF",
      "prenoms": "Wagane",
      "dateNaissance": "17/07/1970",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995004QU",
      "nom": "DIOUF",
      "prenoms": "Wagane",
      "dateNaissance": "17/07/1970",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 12,
      "numero": "19950045B",
      "nom": "DIOP",
      "prenoms": "Serigne",
      "dateNaissance": "05/09/1971",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 1 Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 15,
      "numero": "1996006RV",
      "nom": "WAGUE",
      "prenoms": "Souaréba",
      "dateNaissance": "20/09/1977",
      "lieuNaissance": "TOUBA DIAKHA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Histoire",
      "typeEtudiant": "ancien",
      "moyenne": 13,
      "numero": "1995001KT",
      "nom": "SOW",
      "prenoms": "Assane",
      "dateNaissance": "18/03/1975",
      "lieuNaissance": "KAEL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Histoire",
      "typeEtudiant": "ancien",
      "moyenne": 6,
      "numero": "1995005E0",
      "nom": "DIALLO",
      "prenoms": "Ibrahima",
      "dateNaissance": "13/02/1968",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Histoire",
      "typeEtudiant": "ancien",
      "moyenne": 12,
      "numero": "1995003AK",
      "nom": "DIALLO",
      "prenoms": "Sadio",
      "dateNaissance": "15/09/1970",
      "lieuNaissance": "BIGNONA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Lettres Modernes",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 3 Lettres Modernes",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700ALW",
      "nom": "GUEYE",
      "prenoms": "Laobé",
      "dateNaissance": "07/07/1977",
      "lieuNaissance": "DAHRA DJOLOFF"
    },
    {
      "sessionId": "Session 2",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Recherche Droit Public",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1997008X1",
      "nom": "DIOP",
      "prenoms": "Cheikh",
      "dateNaissance": "18/01/1977",
      "lieuNaissance": "TOCKY"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Recherche Droit Public",
      "typeEtudiant": "ancien",
      "moyenne": 12,
      "numero": "1997008X1",
      "nom": "DIOP",
      "prenoms": "Cheikh",
      "dateNaissance": "18/01/1977",
      "lieuNaissance": "TOCKY"
    },
    {
      "sessionId": "Session 1",
      "departement": "....",
      "etablissement": "C.E.S.T.I.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Medias - Communication",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199500036",
      "nom": "MANE",
      "prenoms": "Bacary",
      "dateNaissance": "10/03/1967",
      "lieuNaissance": "SIMBANDI"
    },
    {
      "sessionId": "Session 2",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 2 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199600897",
      "nom": "DIOUF",
      "prenoms": "Amadou",
      "dateNaissance": "04/03/1974",
      "lieuNaissance": "GUINGUINEO"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 2 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 8,
      "numero": "199600897",
      "nom": "DIOUF",
      "prenoms": "Amadou",
      "dateNaissance": "04/03/1974",
      "lieuNaissance": "GUINGUINEO"
    },
    {
      "sessionId": "Session 2",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 2 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995001T3",
      "nom": "BARRO",
      "prenoms": "Mahamadou Lamine",
      "dateNaissance": "17/08/1974",
      "lieuNaissance": "KOLDA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 2 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 8,
      "numero": "1995001T3",
      "nom": "BARRO",
      "prenoms": "Mahamadou Lamine",
      "dateNaissance": "17/08/1974",
      "lieuNaissance": "KOLDA"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123456789123",
      "niveauFormation": "Licence 1 Sciences Juridiques",
      "typeEtudiant": "nouveau bachelier",
      "moyenne": 14,
      "numero": "202006TKR",
      "nom": "NGOM",
      "prenoms": "Fatou",
      "dateNaissance": "27/05/1992",
      "lieuNaissance": "DJILOR SALOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123456789123",
      "niveauFormation": "Licence 1 Sciences Juridiques",
      "typeEtudiant": "nouveau bachelier",
      "moyenne": 14,
      "numero": "202006TKQ",
      "nom": "SENE",
      "prenoms": "Mor",
      "dateNaissance": "21/01/1996",
      "lieuNaissance": "DJILOR SALOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123456789123",
      "niveauFormation": "Licence 1 Sciences Juridiques",
      "typeEtudiant": "nouveau bachelier",
      "moyenne": 13,
      "numero": "202006TKP",
      "nom": "NDAO",
      "prenoms": "Sira",
      "dateNaissance": "20/01/1997",
      "lieuNaissance": "DJILOR SALOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 1 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "2014065LQ",
      "nom": "SABALY",
      "prenoms": "NIABALY",
      "dateNaissance": "15/03/1996",
      "lieuNaissance": "KAGUITTE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Droit Public",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Licence 1 Sciences Juridiques",
      "typeEtudiant": "ancien",
      "moyenne": 9,
      "numero": "1995003C5",
      "nom": "DIOUF",
      "prenoms": "Ibrahima",
      "dateNaissance": "04/09/1972",
      "lieuNaissance": "NGOTHIE"
    },
    {
      "sessionId": "Session 1",
      "departement": "...",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire Philosophie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995004YW",
      "nom": "DIOUF",
      "prenoms": "Amadou",
      "dateNaissance": "07/08/1968",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 2",
      "departement": "Citoyenneté, Droits de l'Homme,Action Humanitaire(I.D.H.P)",
      "etablissement": "F.S.J.P.",
      "numIdentite": "123654789",
      "niveauFormation": "Master 2 Professionnel  Citoyenneté, Droits de l'Homme,Action Humanitaire(I.D.H.P)",
      "typeEtudiant": "ancien",
      "moyenne": 10,
      "numero": "19950058X",
      "nom": "BARRO",
      "prenoms": "El Hadji Macky",
      "dateNaissance": "04/04/1973",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "....",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Doctorat de Thèse Unique en Arts, Cultures et Civilisations",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995004AN",
      "nom": "DIAGNE",
      "prenoms": "Ibrahima Khalilou",
      "dateNaissance": "04/01/1974",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "....",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Doctorat de Thèse Unique en Arts, Cultures et Civilisations",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995006J2",
      "nom": "THIOUNE",
      "prenoms": "Papa Saliou",
      "dateNaissance": "02/04/1974",
      "lieuNaissance": "DIOURBEL"
    },
    {
      "sessionId": "Session 1",
      "departement": "....",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Doctorat de Thèse Unique en Arts, Cultures et Civilisations",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950022H",
      "nom": "BA",
      "prenoms": "Dieynaba",
      "dateNaissance": "11/03/1969",
      "lieuNaissance": "KOUNGHEUL"
    },
    {
      "sessionId": "Session 1",
      "departement": "....",
      "etablissement": "F.L.S.H.",
      "numIdentite": "123654789",
      "niveauFormation": "Doctorat de Thèse Unique en Arts, Cultures et Civilisations",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1996006T2",
      "nom": "SOW",
      "prenoms": "Mamadou",
      "dateNaissance": "10/10/1976",
      "lieuNaissance": "THIES"
    },
    {
      "sessionId": "Session 1",
      "departement": "Langues Romanes",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Certificat d'Aptitude à l'Enseignement Secondaire  en Portugais",
      "typeEtudiant": "ancien",
      "moyenne": 6,
      "numero": "1995006H9",
      "nom": "NDAO",
      "prenoms": "Moussa",
      "dateNaissance": "08/03/1968",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Langues Romanes",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Espagnol",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995002MS",
      "nom": "BA",
      "prenoms": "Idy Mamadou",
      "dateNaissance": "14/05/1969",
      "lieuNaissance": "NENETTE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Lettres",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Lettres",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19960083R",
      "nom": "NDIAYE",
      "prenoms": "Mame Massow",
      "dateNaissance": "13/08/1976",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995000K7",
      "nom": "SEYE",
      "prenoms": "Serigne Amidou",
      "dateNaissance": "29/08/1974",
      "lieuNaissance": "BAMBEY"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950058M",
      "nom": "GAYE",
      "prenoms": "Assane",
      "dateNaissance": "05/05/1966",
      "lieuNaissance": "PIKINE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995002S5",
      "nom": "BA",
      "prenoms": "Demba",
      "dateNaissance": "04/05/1970",
      "lieuNaissance": "TENEFOUL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995002II",
      "nom": "NIANG",
      "prenoms": "Talla",
      "dateNaissance": "27/08/1974",
      "lieuNaissance": "KEBEMER"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 7,
      "numero": "1995000B6",
      "nom": "SARR",
      "prenoms": "Assane",
      "dateNaissance": "24/02/1973",
      "lieuNaissance": "PEYE GOYE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Certificat d'Aptitude à l'Enseignement Secondaire en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 14,
      "numero": "1995004QU",
      "nom": "DIOUF",
      "prenoms": "Wagane",
      "dateNaissance": "17/07/1970",
      "lieuNaissance": "FATICK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat à l'Enseignement dans les Collèges d'Enseignement Moyen en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1996007UA",
      "nom": "MANE",
      "prenoms": "Ousseynou",
      "dateNaissance": "17/05/1976",
      "lieuNaissance": "COUBALAN"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat à l'Enseignement dans les Collèges d'Enseignement Moyen en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995001X2",
      "nom": "GACKOU",
      "prenoms": "Cheikh",
      "dateNaissance": "27/09/1973",
      "lieuNaissance": "MAROUTTE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Anglais",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat à l'Enseignement dans les Collèges d'Enseignement Moyen en Anglais",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199500117",
      "nom": "DIOP",
      "prenoms": "Biram",
      "dateNaissance": "10/10/1973",
      "lieuNaissance": "KAOLACK"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire-Géographie",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Histoire-Géographie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199500562",
      "nom": "DIENG",
      "prenoms": "Abdoulaye",
      "dateNaissance": "01/03/1968",
      "lieuNaissance": "BAMBEY"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire-Géographie",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Histoire-Géographie",
      "typeEtudiant": "ancien",
      "moyenne": 6,
      "numero": "199500562",
      "nom": "DIENG",
      "prenoms": "Abdoulaye",
      "dateNaissance": "01/03/1968",
      "lieuNaissance": "BAMBEY"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire-Géographie",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Histoire-Géographie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "19950049X",
      "nom": "HOUNDECHANDJI",
      "prenoms": "Akouwa Marie Francoise",
      "dateNaissance": "19/02/1974",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire-Géographie",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du CAE-CEM en Histoire Géographie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995001CU",
      "nom": "MBAYE",
      "prenoms": "Ibrahima",
      "dateNaissance": "13/09/1966",
      "lieuNaissance": "RUFISQUE"
    },
    {
      "sessionId": "Session 1",
      "departement": "Histoire-Géographie",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du CAE-CEM en Histoire Géographie",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995000RF",
      "nom": "DIEDHIOU",
      "prenoms": "Moussa",
      "dateNaissance": "18/02/1974",
      "lieuNaissance": "MARSASSOUM"
    },
    {
      "sessionId": "Session 1",
      "departement": "Arabe",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du Certificat d'Aptitude à l'Enseignement Secondaire en Arabe",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "1995001RR",
      "nom": "SANE",
      "prenoms": "Abdou Karim",
      "dateNaissance": "10/04/1973",
      "lieuNaissance": "YEUMBEUL"
    },
    {
      "sessionId": "Session 1",
      "departement": "Allemand",
      "etablissement": "F.A.S.T.E.F.",
      "numIdentite": "123654789",
      "niveauFormation": "Première Année du Certificat d'Aptitude à l'Enseignement Secondaire en Allemand",
      "typeEtudiant": "ancien",
      "moyenne": 7,
      "numero": "19950027E",
      "nom": "NIABALY",
      "prenoms": "Aissatou",
      "dateNaissance": "10/06/1974",
      "lieuNaissance": "DAKAR"
    },
    {
      "sessionId": "Session 1",
      "departement": "Chirurgie et Spécialités Chirurgicales",
      "etablissement": "F.M.P.O.",
      "numIdentite": "123654789",
      "niveauFormation": "Deuxième Année du d.e.s oto-rhino-laryngologie (orl)",
      "typeEtudiant": "ancien",
      "moyenne": 11,
      "numero": "199700AVY",
      "nom": "BA",
      "prenoms": "Pape Yakhya",
      "dateNaissance": "25/06/1978",
      "lieuNaissance": "MEDINA GOUNASS"
    }
  ]
  constructor( private httpClient: HttpClient, public jwtHelper: JwtHelperService) { }

  /**
   * Stock le token si l'utilisateur est connecter
   * @returns {boolean}
   */
   public hasToken(): boolean {
    return !!localStorage.getItem('token');
  }

  /**
   * Connexion de l'utilisateur et prend en parametre, le login et le password
   * @param username
   * @param password
   */
  // tslint:disable-next-line:typedef
   isLogin(username: string, password: string){
    const body = '{"username":"' + username + '","password":"' + password + '"}';
    const header = new HttpHeaders({'Content-Type': 'application/json'});
    return this.httpClient.post(`${envVars.url}/login_check`, body, {headers: header});
  }
  /**
   * Deconnexion avec la destruction du token
   */
  // tslint:disable-next-line:typedef
  isLogOut(){
    localStorage.removeItem('token');
    localStorage.clear()
  }
  /**
   * Methode pour lister les Utilisateurs
   */
   readApiEtudiant(): Observable<EtudiantModel[]> {
    return this.httpClient.get<EtudiantModel[]>('/gestionPedagoqique/etudiantCoud/31');
   }
   addEtudiant(etudiant: any): Observable<EtudiantModel> {
    return this.httpClient.post<EtudiantModel>(envVars.url+'/etudiant/inscription', etudiant, {headers: this.headers});
  }
  addAdmin(etudiant: any): Observable<EtudiantModel> {
    return this.httpClient.post<EtudiantModel>(envVars.url+'/admin/inscription', etudiant, {headers: this.headers});
  }
  getAllAdmin(page: number): Observable<EtudiantModel[]>{
    return this.httpClient.get<EtudiantModel[]>(envVars.url+'/admin/liste?typeuser=admin&&itemsPerPage=10&page='+page, {headers: this.headers});
  }
  archiveAdmin(objet: any): Observable<EtudiantModel> {
    const body = `{"archivage": ${!objet.archivage}}`;
    const header = new HttpHeaders({'Content-Type': 'application/json'});
    return this.httpClient.put<EtudiantModel>(envVars.url+'/admin/archivage' + '/' +  objet.id, body, {headers: header});
  }
  updateInfoAdmin(username: any): Observable<any>{
    return this.httpClient.put<any>(envVars.url+'/admin/archivage' + '/' + username.id, username, {headers: this.headers});
  }

  i = 1
  chargerEtudiantsCollection(){
    if(this.etudiantCollection[this.i]){
      this.httpClient.post<any> (envVars.url+'/etudiant_apis',this.etudiantCollection[this.i]).subscribe(
        (data) => {
          console.log(data);
        })
      this.i++
      setTimeout(()=>{  
        this.chargerEtudiantsCollection();   
      }, 2000);
    }
  }
}
